//
// Created by gster on 5/24/20.
//

#ifndef SPL_NODETYPES_H
#define SPL_NODETYPES_H

class ASTNode;
class ArgsList;
class ArrayType;
class AssignStmt;
class BinaryExpr;
class CalcExpr;
class CallFactor;
class CallProcStmt;
class CaseExpr;
class CaseExprList;
class CaseStmt;
class CompoundStmt;
class ConstCharValue;
class ConstExprList;
class ConstFactor;
class ConstIntValue;
class ConstPart;
class ConstRealValue;
class ConstValue;
class ConstValueCaseExpr;
class CustomType;
class Direction;
class ElseClause;
class EnumType;
class Expr;
class Expression;
class ExpressionList;
class Factor;
class FieldDecl;
class FieldDeclList;
class ForStmt;
class Function;
class FunctionHead;
class GotoStmt;
class IfStmt;
class IndexFactor;
class IndexLeftValue;
class LabelPart;
class LeftValue;
class MemberFactor;
class MemberLeftValue;
class Name;
class NameCaseExpr;
class NameFactor;
class NameLeftValue;
class NameList;
class NameProcStmt;
class ParaDeclList;
class ParaTypeList;
class Parameters;
class ParenthesesFactor;
class ProcStmt;
class Procedure;
class ProcedureHead;
class Program;
class ProgramHead;
class RangeType;
class ReadProcStmt;
class RecordType;
class RepeatStmt;
class Routine;
class RoutineBody;
class RoutineDecl;
class RoutineHead;
class RoutinePart;
class SimpleType;
class Stmt;
class StmtList;
class SysCallProcStmt;
class SysFunc;
class SysFuncCallFactor;
class SysFuncFactor;
class SysProc;
class SysProcStmt;
class SysType;
class Term;
class TypeDecl;
class TypeDeclList;
class TypeDefinition;
class TypePart;
class VarDecl;
class VarDeclList;
class VarParaList;
class VarPart;
class WhileStmt;

#endif //SPL_NODETYPES_H
