//
// Created by gster on 5/24/20.
//

#ifndef SPL_NODETYPES_H
#define SPL_NODETYPES_H

struct ASTNode;
struct ArgsList;
struct ArrayType;
struct AssignStmt;
struct BinaryExpr
struct CalcExpr;
struct CallFactor;
struct CallProcStmt;
struct CaseExpr;
struct CaseExprList;
struct CaseStmt;
struct CompoundStmt;
struct ConstCharValue;
struct ConstExprList;
struct ConstFactor;
struct ConstIntValue;
struct ConstPart;
struct ConstRealValue;
struct ConstValue;
struct ConstValueCaseExpr;
struct CustomType;
struct Direction;
struct ElseClause;
struct EnumType;
struct Expr;
struct Expression;
struct ExpressionList;
struct Factor;
struct FieldDecl;
struct FieldDeclList;
struct ForStmt;
struct Function;
struct FunctionHead;
struct GotoStmt;
struct IfStmt;
struct IndexFactor;
struct IndexLeftValue;
struct LabelPart;
struct LeftValue;
struct MemberFactor;
struct MemberLeftValue;
struct Name;
struct NameCaseExpr;
struct NameFactor;
struct NameLeftValue;
struct NameList;
struct NameProcStmt;
struct ParaDeclList;
struct ParaTypeList;
struct Parameters;
struct ParenthesesFactor;
struct ProcStmt;
struct Procedure;
struct ProcedureHead;
struct Program;
struct ProgramHead;
struct RangeType;
struct ReadProcStmt;
struct RecordType;
struct RepeatStmt;
struct Routine;
struct RoutineBody;
struct RoutineDecl;
struct RoutineHead;
struct RoutinePart;
struct SimpleType;
struct Stmt;
struct StmtList;
struct SysCallProcStmt;
struct SysFunc;
struct SysFuncCallFactor;
struct SysFuncFactor;
struct SysProc;
struct SysProcStmt;
struct SysType;
struct Term;
struct TypeDecl;
struct TypeDeclList;
struct TypeDefinition;
struct TypePart;
struct VarDecl;
struct VarDeclList;
struct VarParaList;
struct VarPart;
struct WhileStmt;

#endif //SPL_NODETYPES_H
